server:
  error:
    include-stacktrace: never
    include-message: always
    include-exception: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


jwt:
  secret: abbas